name: create file
on:
  workflow_dispatch:

jobs:
  run:
    name: Add a text file
    runs-on: ubuntu-latest

    steps:
      - run: ls -a
      - run: |
          echo ${PWD}

      # ...and then use the action as you would normally do, but providing the path to the repo
      #- uses: EndBug/add-and-commit@v9
      #  with:
      #    message: 'Add the very useful text file'
      #    add: '*.txt --force'
