name: create file
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: ls
      - name: Run a one-line script
        run: ls -a
      - name: Run a one-line script
        run: tree
      - name: run script
        run: bash .github/workflows/createfile.sh
